### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by mateomh** [mateomh/Store-Finder#3]
# Final checklist before submitting the project
- [x] Check the text with grammarly
- [x] Check the text with hemmingway
- [x] Check all the fonts are suited for the site
- [x] Check and fix linter errors locally
- [x] Complete the README.md
